In [1]:
import pandas as pd
import nltk.data
import json
from transformers import BertTokenizer, BertForSequenceClassification, pipeline
from multiprocessing import Pool

#nltk.download('punkt')
sent_detector = nltk.data.load('tokenizers/punkt/english.pickle')

In [2]:
df_filings = pd.read_csv("../data/10K_filings.csv")
df_filings.head()

,accessionNumber,filingDate,reportDate,acceptanceDateTime,act,form,fileNumber,filmNumber,items,size,isXBRL,isInlineXBRL,primaryDocument,primaryDocDescription,ticker,cik,text
0,0000320193-22-000108,2022-10-28,2022-09-24,2022-10-27T18:01:14.000Z,34.0,10-K,001-36743,221338448,NaN,10332356,1,1,aapl-20220924.htm,10-K,AAPL,320193,10-K\n 1\n aapl-20220924.htm\n 10-K\n \n \n \n...
1,0000320193-21-000105,2021-10-29,2021-09-25,2021-10-28T18:04:28.000Z,34.0,10-K,001-36743,211359752,NaN,10502096,1,1,aapl-20210925.htm,10-K,AAPL,320193,10-K\n 1\n aapl-20210925.htm\n 10-K\n \n \n \n...
2,0000320193-20-000096,2020-10-30,2020-09-26,2020-10-29T18:06:25.000Z,34.0,10-K,001-36743,201273977,NaN,12502600,1,1,aapl-20200926.htm,10-K,AAPL,320193,10-K\n 1\n aapl-20200926.htm\n 10-K\n \n \n \n...
3,0000320193-19-000119,2019-10-31,2019-09-28,2019-10-30T18:12:36.000Z,34.0,10-K,001-36743,191181423,NaN,12861616,1,1,a10-k20199282019.htm,10-K,AAPL,320193,10-K\n 1\n a10-k20199282019.htm\n 10-K\n \n \n...
4,0000320193-18-000145,2018-11-05,2018-09-29,2018-11-05T08:01:40.000Z,34.0,10-K,001-36743,181158788,NaN,12275572,1,0,a10-k20189292018.htm,10-K,AAPL,320193,10-K\n 1\n a10-k20189292018.htm\n 10-K\n \n \n...

In [3]:
sentences = sent_detector.tokenize(df_filings.text[0].strip())
len(sentences)

970

In [4]:
import pandas as pd
import nltk.data
sent_detector = nltk.data.load('tokenizers/punkt/english.pickle')
import json
from transformers import BertTokenizer, BertForSequenceClassification, pipeline

# FinBERT model
finbert = BertForSequenceClassification.from_pretrained('yiyanghkust/finbert-esg',num_labels=4)
tokenizer = BertTokenizer.from_pretrained('yiyanghkust/finbert-esg')
nlp = pipeline("text-classification", model=finbert, tokenizer=tokenizer)

In [5]:

# download necessary filings data
df_filings = pd.read_csv("../data/10K_filings.csv")
df_filings.head()

,accessionNumber,filingDate,reportDate,acceptanceDateTime,act,form,fileNumber,filmNumber,items,size,isXBRL,isInlineXBRL,primaryDocument,primaryDocDescription,ticker,cik,text
0,0000320193-22-000108,2022-10-28,2022-09-24,2022-10-27T18:01:14.000Z,34.0,10-K,001-36743,221338448,NaN,10332356,1,1,aapl-20220924.htm,10-K,AAPL,320193,10-K\n 1\n aapl-20220924.htm\n 10-K\n \n \n \n...
1,0000320193-21-000105,2021-10-29,2021-09-25,2021-10-28T18:04:28.000Z,34.0,10-K,001-36743,211359752,NaN,10502096,1,1,aapl-20210925.htm,10-K,AAPL,320193,10-K\n 1\n aapl-20210925.htm\n 10-K\n \n \n \n...
2,0000320193-20-000096,2020-10-30,2020-09-26,2020-10-29T18:06:25.000Z,34.0,10-K,001-36743,201273977,NaN,12502600,1,1,aapl-20200926.htm,10-K,AAPL,320193,10-K\n 1\n aapl-20200926.htm\n 10-K\n \n \n \n...
3,0000320193-19-000119,2019-10-31,2019-09-28,2019-10-30T18:12:36.000Z,34.0,10-K,001-36743,191181423,NaN,12861616,1,1,a10-k20199282019.htm,10-K,AAPL,320193,10-K\n 1\n a10-k20199282019.htm\n 10-K\n \n \n...
4,0000320193-18-000145,2018-11-05,2018-09-29,2018-11-05T08:01:40.000Z,34.0,10-K,001-36743,181158788,NaN,12275572,1,0,a10-k20189292018.htm,10-K,AAPL,320193,10-K\n 1\n a10-k20189292018.htm\n 10-K\n \n \n...

In [6]:
import torch

device = torch.device("mps")
# FinBERT model
finbert = BertForSequenceClassification.from_pretrained('yiyanghkust/finbert-esg',num_labels=4)
tokenizer = BertTokenizer.from_pretrained('yiyanghkust/finbert-esg')
#nlp = pipeline("text-classification", model=finbert, tokenizer=tokenizer)

inputs    = tokenizer(sentences[:32], return_tensors="pt", truncation = True, padding = True, max_length = 512).to(device)
finbert   = finbert.to(device)
outputs   = finbert(**inputs)

In [11]:
device = torch.device("mps")

In [5]:
report = df_filings.text[0]
filings_sentences = sent_detector.tokenize(report.strip())
report_sentences = pd.DataFrame(filings_sentences, columns = ["sentence"])
#report_sentences.loc[:, "id"] = list(range(report_sentences.shape[0]))
report_sentences

                                              sentence
0    10-K\n 1\n aapl-20220924.htm\n 10-K\n \n \n \n...
1    Commission File Number:  001-36743 Apple Inc. ...
2                         Employer Identification No.)
3    One Apple Park Way Cupertino ,  California 950...
4    Yes    ☒      No   ☐ Indicate by check mark if...
..                                                 ...
965  Apple Inc. | 2022 Form 10-K | 57 SIGNATURES Pu...
966  Date: October 27, 2022 Apple Inc. By: /s/ Luca...
967  Pursuant to the requirements of the Securities...
968            Bell Director October 27, 2022 JAMES A.
969  BELL /s/    Al Gore Director October 27, 2022 ...

[970 rows x 1 columns]

In [11]:
def esg_sentence_disclosure(sentence, idx):    
    try:
        result = nlp(sentence)
        if not(result[0]["label"] == "None"):
            esg_disclosure[result[0]["label"]]['sentence_id'].append(idx)
            sentences_tmp = report_sentences.loc[max(idx-1, 0): min(report_sentences.shape[0], idx + 1)].sentence.values.tolist()
            esg_disclosure[result[0]["label"]]['content'].append(" ".join(sentences_tmp))
    except:
        #nbr_of_sentences_with_more_than_max_tokens += 1
        pass

report = df_filings.text[0]
filings_sentences = sent_detector.tokenize(report.strip())
report_sentences = pd.DataFrame(filings_sentences, columns = ["sentence"])
report_sentences.loc[:, "id"] = list(range(report_sentences.shape[0]))

esg_disclosure = {}
esg_disclosure['Environmental'] = {}
esg_disclosure['Environmental']["sentence_id"] = []
esg_disclosure['Environmental']["content"] = []
esg_disclosure['Social'] = {}
esg_disclosure['Social']["sentence_id"] = []
esg_disclosure['Social']["content"] = []
esg_disclosure['Governance'] = {}
esg_disclosure['Governance']["sentence_id"] = []
esg_disclosure['Governance']["content"] = []

nbr_of_sentences_with_more_than_max_tokens = 0

for idx in range(report_sentences.shape[0]):
    esg_sentence_disclosure(report_sentences.loc[idx, "sentence"], idx)

In [12]:
esg_disclosure

{'Environmental': {'sentence_id': [122, 168, 370, 371, 372, 373, 374],
  'content': ['The Company periodically provides certain information for investors on its corporate website, www.apple.com, and its investor relations website, investor.apple.com. This includes press releases and other information about financial performance, information on environmental, social and governance matters, and details related to the Company’s annual meeting of shareholders. The information contained on the websites referenced in this Form 10-K is not incorporated by reference into this filing.',
   'In addition, such operations and facilities are subject to the risk of interruption by fire, power shortages, nuclear power plant accidents and other industrial accidents, terrorist attacks and other hostile acts, ransomware and other cybersecurity attacks, labor disputes, public health issues, including pandemics such as the COVID-19 pandemic, and other events beyond the Company’s control. Global climate change is resulting in certain types of natural disasters occurring more frequently or with more intense effects. Such events can make it difficult or impossible for the Company to manufacture and deliver products to its customers, create delays and inefficiencies in the Company’s supply and manufacturing chain, and result in slowdowns and outages to the Company’s service offerings.',
   'As a result, the Company’s products could be delayed or prohibited from importation, either of which could materially adversely affect the Company’s business, reputation, results of operations and financial condition. Expectations relating to environmental, social and governance considerations expose the Company to potential liabilities, increased costs, reputational harm, and other adverse effects on the Company’s business. Many governments, regulators, investors, employees, customers and other stakeholders are increasingly focused on environmental, social and governance considerations relating to businesses, including climate change and greenhouse gas emissions, human and civil rights, and diversity, equity and inclusion.',
   'Expectations relating to environmental, social and governance considerations expose the Company to potential liabilities, increased costs, reputational harm, and other adverse effects on the Company’s business. Many governments, regulators, investors, employees, customers and other stakeholders are increasingly focused on environmental, social and governance considerations relating to businesses, including climate change and greenhouse gas emissions, human and civil rights, and diversity, equity and inclusion. In addition, the Company makes statements about its environmental, social and governance goals and initiatives through its environmental, social and governance report, its other non-financial reports, information provided on its website, press statements and other communications.',
   'Many governments, regulators, investors, employees, customers and other stakeholders are increasingly focused on environmental, social and governance considerations relating to businesses, including climate change and greenhouse gas emissions, human and civil rights, and diversity, equity and inclusion. In addition, the Company makes statements about its environmental, social and governance goals and initiatives through its environmental, social and governance report, its other non-financial reports, information provided on its website, press statements and other communications. Responding to these environmental, social and governance considerations and implementation of these goals and initiatives involves risks and uncertainties, requires investments, and depends in part on third-party performance or data that is outside the Company’s control.',
   'In addition, the Company makes statements about its environmental, social and governance goals and initiatives through its environmental, social and governance report, its other non-financial reports, information provided on its website, press statements and other communications. Responding to these environmental, social and governance considerations and implementation of these goals and initiatives involves risks and uncertainties, requires investments, and depends in part on third-party performance or data that is outside the Company’s control. The Company cannot guarantee that it will achieve its announced environmental, social and governance goals and initiatives.',
   'Responding to these environmental, social and governance considerations and implementation of these goals and initiatives involves risks and uncertainties, requires investments, and depends in part on third-party performance or data that is outside the Company’s control. The Company cannot guarantee that it will achieve its announced environmental, social and governance goals and initiatives. In addition, some stakeholders may disagree with the Company’s goals and initiatives.']},
 'Social': {'sentence_id': [104,
   105,
   106,
   108,
   109,
   110,
   111,
   112,
   113,
   114,
   115,
   116,
   117,
   118,
   141,
   142,
   146,
   173,
   289,
   292,
   310,
   313,
   319,
   320,
   321,
   503,
   506],
  'content': ['Net sales can also be affected when consumers and distributors anticipate a product introduction. Human Capital The Company believes it has a talented, motivated and dedicated team, and works to create an inclusive, safe and supportive environment for all of its team members. As of September\xa024, 2022, the Company had approximately 164,000 full-time equivalent employees.',
   'Human Capital The Company believes it has a talented, motivated and dedicated team, and works to create an inclusive, safe and supportive environment for all of its team members. As of September\xa024, 2022, the Company had approximately 164,000 full-time equivalent employees. Workplace Practices and Policies The Company is an equal opportunity employer committed to inclusion and diversity and to providing a workplace free of harassment or discrimination.',
   'As of September\xa024, 2022, the Company had approximately 164,000 full-time equivalent employees. Workplace Practices and Policies The Company is an equal opportunity employer committed to inclusion and diversity and to providing a workplace free of harassment or discrimination. Compensation and Benefits The Company believes that compensation should be competitive and equitable, and should enable employees to share in the Company’s success.',
   'Compensation and Benefits The Company believes that compensation should be competitive and equitable, and should enable employees to share in the Company’s success. The Company recognizes its people are most likely to thrive when they have the resources to meet their needs and the time and support to succeed in their professional and personal lives. In support of this, the Company offers a wide variety of benefits for employees around the world and invests in tools and resources that are designed to support employees’ individual growth and development.',
   'The Company recognizes its people are most likely to thrive when they have the resources to meet their needs and the time and support to succeed in their professional and personal lives. In support of this, the Company offers a wide variety of benefits for employees around the world and invests in tools and resources that are designed to support employees’ individual growth and development. Inclusion and Diversity The Company remains committed to its vision to build and sustain a more inclusive workforce that is representative of the communities it serves.',
   'In support of this, the Company offers a wide variety of benefits for employees around the world and invests in tools and resources that are designed to support employees’ individual growth and development. Inclusion and Diversity The Company remains committed to its vision to build and sustain a more inclusive workforce that is representative of the communities it serves. The Company continues to work to increase diverse representation at every level, foster an inclusive culture, and support equitable pay and access to opportunity for all employees.',
   'Inclusion and Diversity The Company remains committed to its vision to build and sustain a more inclusive workforce that is representative of the communities it serves. The Company continues to work to increase diverse representation at every level, foster an inclusive culture, and support equitable pay and access to opportunity for all employees. Engagement The Company believes that open and honest communication among team members, managers and leaders helps create an open, collaborative work environment where everyone can contribute, grow and succeed.',
   'The Company continues to work to increase diverse representation at every level, foster an inclusive culture, and support equitable pay and access to opportunity for all employees. Engagement The Company believes that open and honest communication among team members, managers and leaders helps create an open, collaborative work environment where everyone can contribute, grow and succeed. Team members are encouraged to come to their managers with questions, feedback or concerns, and the Company conducts surveys that gauge employee sentiment in areas like career development, manager performance and inclusivity.',
   'Engagement The Company believes that open and honest communication among team members, managers and leaders helps create an open, collaborative work environment where everyone can contribute, grow and succeed. Team members are encouraged to come to their managers with questions, feedback or concerns, and the Company conducts surveys that gauge employee sentiment in areas like career development, manager performance and inclusivity. Health and Safety The Company is committed to protecting its team members everywhere it operates.',
   'Team members are encouraged to come to their managers with questions, feedback or concerns, and the Company conducts surveys that gauge employee sentiment in areas like career development, manager performance and inclusivity. Health and Safety The Company is committed to protecting its team members everywhere it operates. The Company identifies potential workplace risks in order to develop measures to mitigate possible hazards.',
   'Health and Safety The Company is committed to protecting its team members everywhere it operates. The Company identifies potential workplace risks in order to develop measures to mitigate possible hazards. The Company supports employees with general safety, security and crisis management training, and by putting specific programs in place for those working in potentially high-hazard environments.',
   'The Company identifies potential workplace risks in order to develop measures to mitigate possible hazards. The Company supports employees with general safety, security and crisis management training, and by putting specific programs in place for those working in potentially high-hazard environments. Additionally, the Company works to protect the safety and security of its team members, visitors and customers through its global security team.',
   'The Company supports employees with general safety, security and crisis management training, and by putting specific programs in place for those working in potentially high-hazard environments. Additionally, the Company works to protect the safety and security of its team members, visitors and customers through its global security team. The Company has also taken additional health and safety measures during the COVID-19 pandemic.',
   'Additionally, the Company works to protect the safety and security of its team members, visitors and customers through its global security team. The Company has also taken additional health and safety measures during the COVID-19 pandemic. Available Information The Company’s Annual Reports on Form 10-K, Quarterly Reports on Form 10-Q, Current Reports on Form 8-K, and amendments to reports filed pursuant to Sections 13(a) and 15(d) of the Securities Exchange Act of 1934, as amended (the “Exchange Act”), are filed with the U.S. Securities and Exchange Commission (the “SEC”).',
   'The Company’s business, results of operations, financial condition and stock price have been adversely affected and could in the future be materially adversely affected by the COVID-19 pandemic. COVID-19 has had, and continues to have, a significant impact around the world, prompting governments and businesses to take unprecedented measures in response. Such measures have included restrictions on travel and business operations, temporary closures of businesses, and quarantine and shelter-in-place orders.',
   'COVID-19 has had, and continues to have, a significant impact around the world, prompting governments and businesses to take unprecedented measures in response. Such measures have included restrictions on travel and business operations, temporary closures of businesses, and quarantine and shelter-in-place orders. The COVID-19 pandemic has at times significantly curtailed global economic activity and caused significant volatility and disruption in global financial markets.',
   'During the course of the pandemic, certain of the Company’s component suppliers and manufacturing and logistical service providers have experienced disruptions, resulting in supply shortages that affected sales worldwide, and similar disruptions could occur in the future. Public safety measures can also adversely impact consumer demand for the Company’s products and services in affected areas. Apple Inc. | 2022 Form 10-K | 5 The Company continues to monitor the situation and take appropriate actions in accordance with the recommendations and requirements of relevant authorities.',
   'Apple Inc. | 2022 Form 10-K | 6 The Company’s operations are also subject to the risks of industrial accidents at its suppliers and contract manufacturers. While the Company’s suppliers are required to maintain safe working environments and operations, an industrial accident could occur and could result in serious injuries or loss of life, disruption to the Company’s business, and harm to the Company’s reputation. Major public health issues, including pandemics such as the COVID-19 pandemic, have adversely affected, and could in the future materially adversely affect, the Company due to their impact on the global economy and demand for consumer products; the imposition of protective public safety measures, such as stringent employee travel restrictions and limitations on freight services and the movement of products between regions; and disruptions in the Company’s supply chain and sales and distribution channels, resulting in interruptions of the supply of current products and delays in production ramps of new products.',
   'There can be no assurance the Company will be able to develop or license such solutions at a reasonable cost and in a timely manner. Apple Inc. | 2022 Form 10-K | 10 The Company’s success depends largely on the talents and efforts of its team members, the continued service and availability of highly skilled employees, including key personnel, and the Company’s ability to nurture its distinctive and inclusive culture. Much of the Company’s future success depends on the talents and efforts of its team members, the continued availability and service of key personnel, including its Chief Executive Officer, executive team and other highly skilled employees.',
   'Experienced personnel in the technology industry are in high demand and competition for their talents is intense, especially in Silicon Valley, where most of the Company’s key personnel are located. In addition to intense competition for talent, workforce dynamics are constantly evolving. If the Company does not manage changing workforce dynamics effectively, it could materially adversely affect the Company’s culture, reputation and operational flexibility.',
   'Losses or unauthorized access to or releases of confidential information, including personal information, could subject the Company to significant reputational, financial, legal and operational consequences. The Company’s business requires it to use and store confidential information, including personal information, with respect to the Company’s customers and employees. The Company devotes significant resources to network and data security, including through the use of encryption and other security measures intended to protect its systems and data.',
   'But these measures cannot provide absolute security, and losses or unauthorized access to or releases of confidential information occur and could materially adversely affect the Company’s business, reputation, results of operations and financial condition. The Company’s business also requires it to share confidential information with suppliers and other third parties. The Company relies on global suppliers that are also exposed to ransomware and other malicious attacks that can disrupt business operations.',
   'These attacks seek to compromise the confidentiality, integrity or availability of confidential information or disrupt normal business operations, and could, among other things, impair the Company’s ability to attract and retain customers for its products and services, impact the Company’s stock price, materially damage commercial relationships, and expose the Company to litigation or government investigations, which could result in penalties, fines or judgments against the Company. Globally, attacks are expected to continue accelerating in both frequency and sophistication with increasing use by actors of tools and techniques that are designed to circumvent controls, avoid detection, and remove or obfuscate forensic evidence, all of which hinders the Company’s ability to identify, investigate and recover from incidents. In addition, attacks against the Company and its customers can escalate during periods of severe diplomatic or armed conflict.',
   'Globally, attacks are expected to continue accelerating in both frequency and sophistication with increasing use by actors of tools and techniques that are designed to circumvent controls, avoid detection, and remove or obfuscate forensic evidence, all of which hinders the Company’s ability to identify, investigate and recover from incidents. In addition, attacks against the Company and its customers can escalate during periods of severe diplomatic or armed conflict. Although malicious attacks perpetrated to gain access to confidential information, including personal information, affect many companies across various industries, the Company is at a relatively greater risk of being targeted because of its high profile and the value of the confidential information it creates, owns, manages, stores and processes.',
   'In addition, attacks against the Company and its customers can escalate during periods of severe diplomatic or armed conflict. Although malicious attacks perpetrated to gain access to confidential information, including personal information, affect many companies across various industries, the Company is at a relatively greater risk of being targeted because of its high profile and the value of the confidential information it creates, owns, manages, stores and processes. The Company has implemented systems and processes intended to secure its information technology systems and prevent unauthorized access to or loss of sensitive data, and mitigate the impact of unauthorized access, including through the use of encryption and authentication technologies.',

In [14]:
len(df_filings.text[0].strip().split(" "))

34650

In [10]:
from multiprocessing import Pool

def esg_sentence_disclosure(sentence, idx):    
    try:
        result = nlp(sentence)
        if not(result[0]["label"] == "None"):
            esg_disclosure[result[0]["label"]]['sentence_id'].append(idx)
            sentences_tmp = report_sentences.loc[max(idx-1, 0): min(report_sentences.shape[0], idx + 1)].sentence.values.tolist()
            esg_disclosure[result[0]["label"]]['content'].append(" ".join(sentences_tmp))
    except:
        #nbr_of_sentences_with_more_than_max_tokens += 1
        pass


report = df_filings.text[0]
filings_sentences = sent_detector.tokenize(report.strip())
report_sentences = pd.DataFrame(filings_sentences, columns = ["sentence"])
report_sentences.loc[:, "id"] = list(range(report_sentences.shape[0]))

esg_disclosure = {}
esg_disclosure['Environmental'] = {}
esg_disclosure['Environmental']["sentence_id"] = []
esg_disclosure['Environmental']["content"] = []
esg_disclosure['Social'] = {}
esg_disclosure['Social']["sentence_id"] = []
esg_disclosure['Social']["content"] = []
esg_disclosure['Governance'] = {}
esg_disclosure['Governance']["sentence_id"] = []
esg_disclosure['Governance']["content"] = []

with Pool(4) as pool:
    pool.starmap(esg_sentence_disclosure, zip(report_sentences.sentence.tolist(), report_sentences.index.tolist()))

Process SpawnPoolWorker-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/pool.py", line 114, in worker
    task = get()
           ^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: Can't get attribute 'esg_sentence_disclosure' on <module '__main__' (built-in)>
Process SpawnPoolWorker-2:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/pool.py", line 114, in worker
    task = get()
           ^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: Can't get attribute 'esg_sentence_disclosure' on <module '__main__' (built-in)>
Process SpawnPoolWorker-3:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/pool.py", line 114, in worker
    task = get()
           ^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: Can't get attribute 'esg_sentence_disclosure' on <module '__main__' (built-in)>
Process SpawnPoolWorker-4:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/pool.py", line 114, in worker
    task = get()
           ^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: Can't get attribute 'esg_sentence_disclosure' on <module '__main__' (built-in)>
Process SpawnPoolWorker-5:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/pool.py", line 114, in worker
    task = get()
           ^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: Can't get attribute 'esg_sentence_disclosure' on <module '__main__' (built-in)>
Process SpawnPoolWorker-6:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/pool.py", line 114, in worker
    task = get()
           ^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: Can't get attribute 'esg_sentence_disclosure' on <module '__main__' (built-in)>
Process SpawnPoolWorker-7:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/pool.py", line 114, in worker
    task = get()
           ^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: Can't get attribute 'esg_sentence_disclosure' on <module '__main__' (built-in)>
Process SpawnPoolWorker-8:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/pool.py", line 114, in worker
    task = get()
           ^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: Can't get attribute 'esg_sentence_disclosure' on <module '__main__' (built-in)>
Process SpawnPoolWorker-9:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/pool.py", line 114, in worker
    task = get()
           ^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: Can't get attribute 'esg_sentence_disclosure' on <module '__main__' (built-in)>
Process SpawnPoolWorker-10:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/pool.py", line 114, in worker
    task = get()
           ^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: Can't get attribute 'esg_sentence_disclosure' on <module '__main__' (built-in)>
Process SpawnPoolWorker-11:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/pool.py", line 114, in worker
    task = get()
           ^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: Can't get attribute 'esg_sentence_disclosure' on <module '__main__' (built-in)>
Process SpawnPoolWorker-12:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/pool.py", line 114, in worker
    task = get()
           ^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: Can't get attribute 'esg_sentence_disclosure' on <module '__main__' (built-in)>
Process SpawnPoolWorker-13:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/pool.py", line 114, in worker
    task = get()
           ^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: Can't get attribute 'esg_sentence_disclosure' on <module '__main__' (built-in)>
Process SpawnPoolWorker-14:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/pool.py", line 114, in worker
    task = get()
           ^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: Can't get attribute 'esg_sentence_disclosure' on <module '__main__' (built-in)>
Process SpawnPoolWorker-15:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/pool.py", line 114, in worker
    task = get()
           ^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: Can't get attribute 'esg_sentence_disclosure' on <module '__main__' (built-in)>
Process SpawnPoolWorker-16:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/pool.py", line 114, in worker
    task = get()
           ^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: Can't get attribute 'esg_sentence_disclosure' on <module '__main__' (built-in)>

KeyboardInterrupt:

In [14]:



def examine_esg_disclosure(report, filename):
    filings_sentences = sent_detector.tokenize(report.strip())
    report_sentences = pd.DataFrame(filings_sentences, columns = ["sentence"])
    report_sentences.loc[:, "id"] = list(range(report_sentences.shape[0]))

    esg_disclosure = {}
    esg_disclosure['Environmental'] = {}
    esg_disclosure['Environmental']["sentence_id"] = []
    esg_disclosure['Environmental']["content"] = []
    esg_disclosure['Social'] = {}
    esg_disclosure['Social']["sentence_id"] = []
    esg_disclosure['Social']["content"] = []
    esg_disclosure['Governance'] = {}
    esg_disclosure['Governance']["sentence_id"] = []
    esg_disclosure['Governance']["content"] = []

    nbr_of_sentences_with_more_than_max_tokens = 0

    for idx, row in report_sentences.iterrows():
        try:
            result = nlp(row["sentence"])
            if not(result[0]["label"] == "None"):
                esg_disclosure[result[0]["label"]]['sentence_id'].append(idx)
                sentences_tmp = report_sentences.loc[max(idx-1, 0): min(report_sentences.shape[0], idx + 1)].sentence.values.tolist()
                esg_disclosure[result[0]["label"]]['content'].append(" ".join(sentences_tmp))
        except:
            #nbr_of_sentences_with_more_than_max_tokens += 1
            pass

    nbr_of_environmental_sentences = len(esg_disclosure["Environmental"]["sentence_id"])
    nbr_of_social_sentences = len(esg_disclosure["Social"]["sentence_id"])
    nbr_of_governance_sentences = len(esg_disclosure["Governance"]["sentence_id"])

    nbr_of_labeled_sentences = report_sentences.shape[0] - nbr_of_sentences_with_more_than_max_tokens


    esg_disclosure["Summary"] = {}
    esg_disclosure["Summary"]["nbr_of_labeled_sentences"] = nbr_of_labeled_sentences
    esg_disclosure["Summary"]["nbr_of_environmental_sentences"] = nbr_of_environmental_sentences
    esg_disclosure["Summary"]["nbr_of_social_sentences"] = nbr_of_social_sentences
    esg_disclosure["Summary"]["nbr_of_governance_sentences"] = nbr_of_governance_sentences


    with open(f"{filename}.json", "w") as fp:
        json.dump(esg_disclosure, fp)

                                              sentence   id
0    10-K\n 1\n aapl-20220924.htm\n 10-K\n \n \n \n...    0
1    Commission File Number:  001-36743 Apple Inc. ...    1
2                         Employer Identification No.)    2
3    One Apple Park Way Cupertino ,  California 950...    3
4    Yes    ☒      No   ☐ Indicate by check mark if...    4
..                                                 ...  ...
965  Apple Inc. | 2022 Form 10-K | 57 SIGNATURES Pu...  965
966  Date: October 27, 2022 Apple Inc. By: /s/ Luca...  966
967  Pursuant to the requirements of the Securities...  967
968            Bell Director October 27, 2022 JAMES A.  968
969  BELL /s/    Al Gore Director October 27, 2022 ...  969

[970 rows x 2 columns]

In [4]:
from transformers import BertTokenizer, BertForSequenceClassification, pipeline

finbert = BertForSequenceClassification.from_pretrained('yiyanghkust/finbert-esg',num_labels=4)
tokenizer = BertTokenizer.from_pretrained('yiyanghkust/finbert-esg')
nlp = pipeline("text-classification", model=finbert, tokenizer=tokenizer)

In [32]:
from tqdm.notebook import tqdm


esg_disclosure = {}
esg_disclosure['Environmental'] = {}
esg_disclosure['Environmental']["sentence_id"] = []
esg_disclosure['Environmental']["content"] = []
esg_disclosure['Social'] = {}
esg_disclosure['Social']["sentence_id"] = []
esg_disclosure['Social']["content"] = []
esg_disclosure['Governance'] = {}
esg_disclosure['Governance']["sentence_id"] = []
esg_disclosure['Governance']["content"] = []

nbr_of_sentences_with_more_than_max_tokens = 0

for idx, row in tqdm(report_sentences.iterrows()):
    #if row["is_in_token_range"]:
    try:
        result = nlp(row["sentence"])
        if not(result[0]["label"] == "None"):
            esg_disclosure[result[0]["label"]]['sentence_id'].append(idx)
            sentences_tmp = report_sentences.loc[max(idx-1, 0): min(report_sentences.shape[0], idx + 1)].sentence.values.tolist()
            esg_disclosure[result[0]["label"]]['content'].append(" ".join(sentences_tmp))
    except:
        nbr_of_sentences_with_more_than_max_tokens += 1

nbr_of_environmental_sentences = len(esg_disclosure["Environmental"]["sentence_id"])
nbr_of_social_sentences = len(esg_disclosure["Social"]["sentence_id"])
nbr_of_governance_sentences = len(esg_disclosure["Governance"]["sentence_id"])

nbr_of_labeled_sentences = report_sentences.shape[0] - nbr_of_sentences_with_more_than_max_tokens


esg_disclosure["Summary"] = {}
esg_disclosure["Summary"]["nbr_of_labeled_sentences"] = nbr_of_labeled_sentences
esg_disclosure["Summary"]["nbr_of_environmental_sentences"] = nbr_of_environmental_sentences
esg_disclosure["Summary"]["nbr_of_social_sentences"] = nbr_of_social_sentences
esg_disclosure["Summary"]["nbr_of_governance_sentences"] = nbr_of_governance_sentences

0it [00:00, ?it/s]

In [36]:
import json

with open('data.json', 'w') as fp:
    json.dump(esg_disclosure, fp)

In [40]:
dict_json["Environmental"]

{'sentence_id': [122, 168, 370, 371, 372, 373, 374],
 'content': ['The Company periodically provides certain information for investors on its corporate website, www.apple.com, and its investor relations website, investor.apple.com. This includes press releases and other information about financial performance, information on environmental, social and governance matters, and details related to the Company’s annual meeting of shareholders. The information contained on the websites referenced in this Form 10-K is not incorporated by reference into this filing.',
  'In addition, such operations and facilities are subject to the risk of interruption by fire, power shortages, nuclear power plant accidents and other industrial accidents, terrorist attacks and other hostile acts, ransomware and other cybersecurity attacks, labor disputes, public health issues, including pandemics such as the COVID-19 pandemic, and other events beyond the Company’s control. Global climate change is resulting in certain types of natural disasters occurring more frequently or with more intense effects. Such events can make it difficult or impossible for the Company to manufacture and deliver products to its customers, create delays and inefficiencies in the Company’s supply and manufacturing chain, and result in slowdowns and outages to the Company’s service offerings.',
  'As a result, the Company’s products could be delayed or prohibited from importation, either of which could materially adversely affect the Company’s business, reputation, results of operations and financial condition. Expectations relating to environmental, social and governance considerations expose the Company to potential liabilities, increased costs, reputational harm, and other adverse effects on the Company’s business. Many governments, regulators, investors, employees, customers and other stakeholders are increasingly focused on environmental, social and governance considerations relating to businesses, including climate change and greenhouse gas emissions, human and civil rights, and diversity, equity and inclusion.',
  'Expectations relating to environmental, social and governance considerations expose the Company to potential liabilities, increased costs, reputational harm, and other adverse effects on the Company’s business. Many governments, regulators, investors, employees, customers and other stakeholders are increasingly focused on environmental, social and governance considerations relating to businesses, including climate change and greenhouse gas emissions, human and civil rights, and diversity, equity and inclusion. In addition, the Company makes statements about its environmental, social and governance goals and initiatives through its environmental, social and governance report, its other non-financial reports, information provided on its website, press statements and other communications.',
  'Many governments, regulators, investors, employees, customers and other stakeholders are increasingly focused on environmental, social and governance considerations relating to businesses, including climate change and greenhouse gas emissions, human and civil rights, and diversity, equity and inclusion. In addition, the Company makes statements about its environmental, social and governance goals and initiatives through its environmental, social and governance report, its other non-financial reports, information provided on its website, press statements and other communications. Responding to these environmental, social and governance considerations and implementation of these goals and initiatives involves risks and uncertainties, requires investments, and depends in part on third-party performance or data that is outside the Company’s control.',
  'In addition, the Company makes statements about its environmental, social and governance goals and initiatives through its environmental, social and governance report, its other non-financial reports, information provided on its website, press statements and other communications. Responding to these environmental, social and governance considerations and implementation of these goals and initiatives involves risks and uncertainties, requires investments, and depends in part on third-party performance or data that is outside the Company’s control. The Company cannot guarantee that it will achieve its announced environmental, social and governance goals and initiatives.',
  'Responding to these environmental, social and governance considerations and implementation of these goals and initiatives involves risks and uncertainties, requires investments, and depends in part on third-party performance or data that is outside the Company’s control. The Company cannot guarantee that it will achieve its announced environmental, social and governance goals and initiatives. In addition, some stakeholders may disagree with the Company’s goals and initiatives.']}

In [39]:
import json

with open("data.json", "r") as fp:
    dict_json = json.load(fp)
dict_json

{'Environmental': {'sentence_id': [122, 168, 370, 371, 372, 373, 374],
  'content': ['The Company periodically provides certain information for investors on its corporate website, www.apple.com, and its investor relations website, investor.apple.com. This includes press releases and other information about financial performance, information on environmental, social and governance matters, and details related to the Company’s annual meeting of shareholders. The information contained on the websites referenced in this Form 10-K is not incorporated by reference into this filing.',
   'In addition, such operations and facilities are subject to the risk of interruption by fire, power shortages, nuclear power plant accidents and other industrial accidents, terrorist attacks and other hostile acts, ransomware and other cybersecurity attacks, labor disputes, public health issues, including pandemics such as the COVID-19 pandemic, and other events beyond the Company’s control. Global climate change is resulting in certain types of natural disasters occurring more frequently or with more intense effects. Such events can make it difficult or impossible for the Company to manufacture and deliver products to its customers, create delays and inefficiencies in the Company’s supply and manufacturing chain, and result in slowdowns and outages to the Company’s service offerings.',
   'As a result, the Company’s products could be delayed or prohibited from importation, either of which could materially adversely affect the Company’s business, reputation, results of operations and financial condition. Expectations relating to environmental, social and governance considerations expose the Company to potential liabilities, increased costs, reputational harm, and other adverse effects on the Company’s business. Many governments, regulators, investors, employees, customers and other stakeholders are increasingly focused on environmental, social and governance considerations relating to businesses, including climate change and greenhouse gas emissions, human and civil rights, and diversity, equity and inclusion.',
   'Expectations relating to environmental, social and governance considerations expose the Company to potential liabilities, increased costs, reputational harm, and other adverse effects on the Company’s business. Many governments, regulators, investors, employees, customers and other stakeholders are increasingly focused on environmental, social and governance considerations relating to businesses, including climate change and greenhouse gas emissions, human and civil rights, and diversity, equity and inclusion. In addition, the Company makes statements about its environmental, social and governance goals and initiatives through its environmental, social and governance report, its other non-financial reports, information provided on its website, press statements and other communications.',
   'Many governments, regulators, investors, employees, customers and other stakeholders are increasingly focused on environmental, social and governance considerations relating to businesses, including climate change and greenhouse gas emissions, human and civil rights, and diversity, equity and inclusion. In addition, the Company makes statements about its environmental, social and governance goals and initiatives through its environmental, social and governance report, its other non-financial reports, information provided on its website, press statements and other communications. Responding to these environmental, social and governance considerations and implementation of these goals and initiatives involves risks and uncertainties, requires investments, and depends in part on third-party performance or data that is outside the Company’s control.',
   'In addition, the Company makes statements about its environmental, social and governance goals and initiatives through its environmental, social and governance report, its other non-financial reports, information provided on its website, press statements and other communications. Responding to these environmental, social and governance considerations and implementation of these goals and initiatives involves risks and uncertainties, requires investments, and depends in part on third-party performance or data that is outside the Company’s control. The Company cannot guarantee that it will achieve its announced environmental, social and governance goals and initiatives.',
   'Responding to these environmental, social and governance considerations and implementation of these goals and initiatives involves risks and uncertainties, requires investments, and depends in part on third-party performance or data that is outside the Company’s control. The Company cannot guarantee that it will achieve its announced environmental, social and governance goals and initiatives. In addition, some stakeholders may disagree with the Company’s goals and initiatives.']},
 'Social': {'sentence_id': [104,
   105,
   106,
   108,
   109,
   110,
   111,
   112,
   113,
   114,
   115,
   116,
   117,
   118,
   141,
   142,
   146,
   173,
   289,
   292,
   310,
   313,
   319,
   320,
   321,
   503,
   506],
  'content': ['Net sales can also be affected when consumers and distributors anticipate a product introduction. Human Capital The Company believes it has a talented, motivated and dedicated team, and works to create an inclusive, safe and supportive environment for all of its team members. As of September\xa024, 2022, the Company had approximately 164,000 full-time equivalent employees.',
   'Human Capital The Company believes it has a talented, motivated and dedicated team, and works to create an inclusive, safe and supportive environment for all of its team members. As of September\xa024, 2022, the Company had approximately 164,000 full-time equivalent employees. Workplace Practices and Policies The Company is an equal opportunity employer committed to inclusion and diversity and to providing a workplace free of harassment or discrimination.',
   'As of September\xa024, 2022, the Company had approximately 164,000 full-time equivalent employees. Workplace Practices and Policies The Company is an equal opportunity employer committed to inclusion and diversity and to providing a workplace free of harassment or discrimination. Compensation and Benefits The Company believes that compensation should be competitive and equitable, and should enable employees to share in the Company’s success.',
   'Compensation and Benefits The Company believes that compensation should be competitive and equitable, and should enable employees to share in the Company’s success. The Company recognizes its people are most likely to thrive when they have the resources to meet their needs and the time and support to succeed in their professional and personal lives. In support of this, the Company offers a wide variety of benefits for employees around the world and invests in tools and resources that are designed to support employees’ individual growth and development.',
   'The Company recognizes its people are most likely to thrive when they have the resources to meet their needs and the time and support to succeed in their professional and personal lives. In support of this, the Company offers a wide variety of benefits for employees around the world and invests in tools and resources that are designed to support employees’ individual growth and development. Inclusion and Diversity The Company remains committed to its vision to build and sustain a more inclusive workforce that is representative of the communities it serves.',
   'In support of this, the Company offers a wide variety of benefits for employees around the world and invests in tools and resources that are designed to support employees’ individual growth and development. Inclusion and Diversity The Company remains committed to its vision to build and sustain a more inclusive workforce that is representative of the communities it serves. The Company continues to work to increase diverse representation at every level, foster an inclusive culture, and support equitable pay and access to opportunity for all employees.',
   'Inclusion and Diversity The Company remains committed to its vision to build and sustain a more inclusive workforce that is representative of the communities it serves. The Company continues to work to increase diverse representation at every level, foster an inclusive culture, and support equitable pay and access to opportunity for all employees. Engagement The Company believes that open and honest communication among team members, managers and leaders helps create an open, collaborative work environment where everyone can contribute, grow and succeed.',
   'The Company continues to work to increase diverse representation at every level, foster an inclusive culture, and support equitable pay and access to opportunity for all employees. Engagement The Company believes that open and honest communication among team members, managers and leaders helps create an open, collaborative work environment where everyone can contribute, grow and succeed. Team members are encouraged to come to their managers with questions, feedback or concerns, and the Company conducts surveys that gauge employee sentiment in areas like career development, manager performance and inclusivity.',
   'Engagement The Company believes that open and honest communication among team members, managers and leaders helps create an open, collaborative work environment where everyone can contribute, grow and succeed. Team members are encouraged to come to their managers with questions, feedback or concerns, and the Company conducts surveys that gauge employee sentiment in areas like career development, manager performance and inclusivity. Health and Safety The Company is committed to protecting its team members everywhere it operates.',
   'Team members are encouraged to come to their managers with questions, feedback or concerns, and the Company conducts surveys that gauge employee sentiment in areas like career development, manager performance and inclusivity. Health and Safety The Company is committed to protecting its team members everywhere it operates. The Company identifies potential workplace risks in order to develop measures to mitigate possible hazards.',
   'Health and Safety The Company is committed to protecting its team members everywhere it operates. The Company identifies potential workplace risks in order to develop measures to mitigate possible hazards. The Company supports employees with general safety, security and crisis management training, and by putting specific programs in place for those working in potentially high-hazard environments.',
   'The Company identifies potential workplace risks in order to develop measures to mitigate possible hazards. The Company supports employees with general safety, security and crisis management training, and by putting specific programs in place for those working in potentially high-hazard environments. Additionally, the Company works to protect the safety and security of its team members, visitors and customers through its global security team.',
   'The Company supports employees with general safety, security and crisis management training, and by putting specific programs in place for those working in potentially high-hazard environments. Additionally, the Company works to protect the safety and security of its team members, visitors and customers through its global security team. The Company has also taken additional health and safety measures during the COVID-19 pandemic.',
   'Additionally, the Company works to protect the safety and security of its team members, visitors and customers through its global security team. The Company has also taken additional health and safety measures during the COVID-19 pandemic. Available Information The Company’s Annual Reports on Form 10-K, Quarterly Reports on Form 10-Q, Current Reports on Form 8-K, and amendments to reports filed pursuant to Sections 13(a) and 15(d) of the Securities Exchange Act of 1934, as amended (the “Exchange Act”), are filed with the U.S. Securities and Exchange Commission (the “SEC”).',
   'The Company’s business, results of operations, financial condition and stock price have been adversely affected and could in the future be materially adversely affected by the COVID-19 pandemic. COVID-19 has had, and continues to have, a significant impact around the world, prompting governments and businesses to take unprecedented measures in response. Such measures have included restrictions on travel and business operations, temporary closures of businesses, and quarantine and shelter-in-place orders.',
   'COVID-19 has had, and continues to have, a significant impact around the world, prompting governments and businesses to take unprecedented measures in response. Such measures have included restrictions on travel and business operations, temporary closures of businesses, and quarantine and shelter-in-place orders. The COVID-19 pandemic has at times significantly curtailed global economic activity and caused significant volatility and disruption in global financial markets.',
   'During the course of the pandemic, certain of the Company’s component suppliers and manufacturing and logistical service providers have experienced disruptions, resulting in supply shortages that affected sales worldwide, and similar disruptions could occur in the future. Public safety measures can also adversely impact consumer demand for the Company’s products and services in affected areas. Apple Inc. | 2022 Form 10-K | 5 The Company continues to monitor the situation and take appropriate actions in accordance with the recommendations and requirements of relevant authorities.',
   'Apple Inc. | 2022 Form 10-K | 6 The Company’s operations are also subject to the risks of industrial accidents at its suppliers and contract manufacturers. While the Company’s suppliers are required to maintain safe working environments and operations, an industrial accident could occur and could result in serious injuries or loss of life, disruption to the Company’s business, and harm to the Company’s reputation. Major public health issues, including pandemics such as the COVID-19 pandemic, have adversely affected, and could in the future materially adversely affect, the Company due to their impact on the global economy and demand for consumer products; the imposition of protective public safety measures, such as stringent employee travel restrictions and limitations on freight services and the movement of products between regions; and disruptions in the Company’s supply chain and sales and distribution channels, resulting in interruptions of the supply of current products and delays in production ramps of new products.',
   'There can be no assurance the Company will be able to develop or license such solutions at a reasonable cost and in a timely manner. Apple Inc. | 2022 Form 10-K | 10 The Company’s success depends largely on the talents and efforts of its team members, the continued service and availability of highly skilled employees, including key personnel, and the Company’s ability to nurture its distinctive and inclusive culture. Much of the Company’s future success depends on the talents and efforts of its team members, the continued availability and service of key personnel, including its Chief Executive Officer, executive team and other highly skilled employees.',
   'Experienced personnel in the technology industry are in high demand and competition for their talents is intense, especially in Silicon Valley, where most of the Company’s key personnel are located. In addition to intense competition for talent, workforce dynamics are constantly evolving. If the Company does not manage changing workforce dynamics effectively, it could materially adversely affect the Company’s culture, reputation and operational flexibility.',
   'Losses or unauthorized access to or releases of confidential information, including personal information, could subject the Company to significant reputational, financial, legal and operational consequences. The Company’s business requires it to use and store confidential information, including personal information, with respect to the Company’s customers and employees. The Company devotes significant resources to network and data security, including through the use of encryption and other security measures intended to protect its systems and data.',
   'But these measures cannot provide absolute security, and losses or unauthorized access to or releases of confidential information occur and could materially adversely affect the Company’s business, reputation, results of operations and financial condition. The Company’s business also requires it to share confidential information with suppliers and other third parties. The Company relies on global suppliers that are also exposed to ransomware and other malicious attacks that can disrupt business operations.',
   'These attacks seek to compromise the confidentiality, integrity or availability of confidential information or disrupt normal business operations, and could, among other things, impair the Company’s ability to attract and retain customers for its products and services, impact the Company’s stock price, materially damage commercial relationships, and expose the Company to litigation or government investigations, which could result in penalties, fines or judgments against the Company. Globally, attacks are expected to continue accelerating in both frequency and sophistication with increasing use by actors of tools and techniques that are designed to circumvent controls, avoid detection, and remove or obfuscate forensic evidence, all of which hinders the Company’s ability to identify, investigate and recover from incidents. In addition, attacks against the Company and its customers can escalate during periods of severe diplomatic or armed conflict.',
   'Globally, attacks are expected to continue accelerating in both frequency and sophistication with increasing use by actors of tools and techniques that are designed to circumvent controls, avoid detection, and remove or obfuscate forensic evidence, all of which hinders the Company’s ability to identify, investigate and recover from incidents. In addition, attacks against the Company and its customers can escalate during periods of severe diplomatic or armed conflict. Although malicious attacks perpetrated to gain access to confidential information, including personal information, affect many companies across various industries, the Company is at a relatively greater risk of being targeted because of its high profile and the value of the confidential information it creates, owns, manages, stores and processes.',
   'In addition, attacks against the Company and its customers can escalate during periods of severe diplomatic or armed conflict. Although malicious attacks perpetrated to gain access to confidential information, including personal information, affect many companies across various industries, the Company is at a relatively greater risk of being targeted because of its high profile and the value of the confidential information it creates, owns, manages, stores and processes. The Company has implemented systems and processes intended to secure its information technology systems and prevent unauthorized access to or loss of sensitive data, and mitigate the impact of unauthorized access, including through the use of encryption and authentication technologies.',

In [26]:
for sentenes in esg_disclosure["Environmental"]["content"]:
    print("-")
    print(sentenes)
    print("-")

-
The Company periodically provides certain information for investors on its corporate website, www.apple.com, and its investor relations website, investor.apple.com. This includes press releases and other information about financial performance, information on environmental, social and governance matters, and details related to the Company’s annual meeting of shareholders. The information contained on the websites referenced in this Form 10-K is not incorporated by reference into this filing.
-
-
In addition, such operations and facilities are subject to the risk of interruption by fire, power shortages, nuclear power plant accidents and other industrial accidents, terrorist attacks and other hostile acts, ransomware and other cybersecurity attacks, labor disputes, public health issues, including pandemics such as the COVID-19 pandemic, and other events beyond the Company’s control. Global climate change is resulting in certain types of natural disasters occurring more frequently or with more intense effects. Such events can make it difficult or impossible for the Company to manufacture and deliver products to its customers, create delays and inefficiencies in the Company’s supply and manufacturing chain, and result in slowdowns and outages to the Company’s service offerings.
-
-
As a result, the Company’s products could be delayed or prohibited from importation, either of which could materially adversely affect the Company’s business, reputation, results of operations and financial condition. Expectations relating to environmental, social and governance considerations expose the Company to potential liabilities, increased costs, reputational harm, and other adverse effects on the Company’s business. Many governments, regulators, investors, employees, customers and other stakeholders are increasingly focused on environmental, social and governance considerations relating to businesses, including climate change and greenhouse gas emissions, human and civil rights, and diversity, equity and inclusion.
-
-
Expectations relating to environmental, social and governance considerations expose the Company to potential liabilities, increased costs, reputational harm, and other adverse effects on the Company’s business. Many governments, regulators, investors, employees, customers and other stakeholders are increasingly focused on environmental, social and governance considerations relating to businesses, including climate change and greenhouse gas emissions, human and civil rights, and diversity, equity and inclusion. In addition, the Company makes statements about its environmental, social and governance goals and initiatives through its environmental, social and governance report, its other non-financial reports, information provided on its website, press statements and other communications.
-
-
Many governments, regulators, investors, employees, customers and other stakeholders are increasingly focused on environmental, social and governance considerations relating to businesses, including climate change and greenhouse gas emissions, human and civil rights, and diversity, equity and inclusion. In addition, the Company makes statements about its environmental, social and governance goals and initiatives through its environmental, social and governance report, its other non-financial reports, information provided on its website, press statements and other communications. Responding to these environmental, social and governance considerations and implementation of these goals and initiatives involves risks and uncertainties, requires investments, and depends in part on third-party performance or data that is outside the Company’s control.
-
-
In addition, the Company makes statements about its environmental, social and governance goals and initiatives through its environmental, social and governance report, its other non-financial reports, information provided on its website, press statements and other communications. Responding to these environmental, social and governance considerations and implementation of these goals and initiatives involves risks and uncertainties, requires investments, and depends in part on third-party performance or data that is outside the Company’s control. The Company cannot guarantee that it will achieve its announced environmental, social and governance goals and initiatives.
-
-
Responding to these environmental, social and governance considerations and implementation of these goals and initiatives involves risks and uncertainties, requires investments, and depends in part on third-party performance or data that is outside the Company’s control. The Company cannot guarantee that it will achieve its announced environmental, social and governance goals and initiatives. In addition, some stakeholders may disagree with the Company’s goals and initiatives.
-

In [48]:
esg_disclosure[result[0]["label"]]

KeyError: 'None'